config/routes.rb
Web::Application.routes.draw do

  mount Mercury::Engine => '/'

  # Support both GET and POST for callbacks
  %w(get post).each do |method|
    send method, "/auth/:provider/callback" => "teachers#update"
  end

  scope ":locale", locale: /es|ca|en/ do
    Mercury::Engine.routes

    devise_for :users

    root :to => "home#index"

    resources :teachers, :except => [:new,:create] do
      get :my_spaces
      resources :web_spaces do
        resources :pages do
          member { put :mercury_update }
        end
      end
    end

    namespace :admin do
      resources :teachers
      resources :departments
    end
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")
end

app/models/teacher.rb
class Teacher < User
  # Associations
  belongs_to :department
  has_many :web_spaces

  # Carrierwave avatar uploader
  mount_uploader :avatar, AvatarUploader

  # Attr Accessibles
  attr_accessible :name, :surname, :birthday, :office, :department_id, :research_area, :avatar

  # Virtual Attributes
  validates :name,    :presence => true
  validates :surname, :presence => true
  validates :email,   :presence => true
  validates :department, :presence => true

  # Searchable
  searchable do
    text :name
    text :surname
    text :email
    text :department
    text :research_area
  end
end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < Admin::AdminController
  inherit_resources
  before_filter :load_departments, :only => [:new,:create,:edit,:update]

  def update
    # Don't update password if it is blank
    params[:teacher][:password] = nil if params[:teacher][:password].blank?
    params[:teacher][:password_confirmation] = nil if params[:teacher][:password].blank?
    update!
  end
end

app/controllers/teachers_controller.rb
#encoding: utf-8
class TeachersController < AuthorizedController
  inherit_resources
  before_filter :load_departments, :only => [:index,:edit,:update]
  #load_and_authorize_resource :teacher

  actions :index, :show, :edit, :update

  def index
    @search = Teacher.search(params[:search])
    @teachers = @search.paginate(:page => params[:page], :per_page => 10)
  end

  def update
    if params[:teacher][:password].blank? || params[:teacher][:password_confirmation].blank?
      params[:teacher][:password] = nil
      params[:teacher][:password_confirmation] = nil
    end
    update! do |format|
      format.html do
        # Don't update password if it is blank
        redirect_to edit_teacher_path(current_user), notice: t('alerts.profile_updated')
      end
    end
  end

  def my_spaces
    @teacher = User.find(current_user)
    @my_web_spaces = WebSpace.where(:teacher_id => current_user)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admin/teachers/_form.html.haml
= form_for [:admin,@teacher], :html => { :multipart => true} do |f|
  -if @teacher.errors.any?
    %div#error_explanation
      %h2= pluralize(@teacher.errors.count, "error")
      %ul
      =@teacher.errors.full_messages.each do |msg|
        %li= msg
  %div.field
    = f.label :nom
    %br
    = f.text_field :name

  %div.field
    = f.label :cognoms
    %br
    = f.text_field :surname

  %div.field
    = f.label :email
    %br
    = f.text_field :email

  %div.field
    = f.label :password
    %br
    = f.password_field :password

  %div.field
    = f.label :password_confirmation
    %br
    = f.password_field :password_confirmation

  %div.field
    = f.label :data_neixament
    %br
    = date_select("teacher", "birthday", :order => [:day, :month, :year], :start_year => 1900, :use_month_numbers => true, :default => { :day => 1, :month => 1 } )

  %div.field
    = f.label :departament
    %br
    = f.select :department_id, @departments.collect{|d| [d.name, d.id]},{:include_blank => true}

  %div.field
    = f.label :area_recerca
    %br
    = f.text_field :research_area

  %div.field
    = f.label :despatx
    %br
    = f.text_field :office

  %div.field
    = f.label :avatar
    %br
    = f.file_field :avatar

  %div.ations
    = f.submit

app/views/admin/teachers/edit.html.haml
%h1 Editing teacher
= render 'form'

= link_to 'Show', @teacher
= link_to 'Back', teachers_path

app/views/admin/teachers/index.html.haml
%h1 Llistat de professors

#admin_table
  %table
    %thead
      %th Nom
      %th Cognom
      %th Data neixament
      %th Email
      %th Departament
      %th Àrea de recerca
      %th Despatx
      %th Avatar

    %tbody
      - @teachers.each do |teacher|
        %tr
          %td= teacher.name
          %td= teacher.surname
          %td= teacher.birthday
          %td= teacher.email
          %td= teacher.department.try(:name)
          %td= teacher.research_area
          %td= teacher.office
          - unless teacher.avatar_url.nil?
            %td= image_tag teacher.avatar_url.to_s
          - else
            %td
          %td= link_to 'Veure perfil', admin_teacher_path(teacher)
          %td= link_to 'Editar', edit_admin_teacher_path(teacher)
          %td= link_to 'Eliminar', admin_teacher_path(teacher), :confirm => 'Estàs segur?', :method => :delete

  = link_to 'Donar d\'alta un professor', new_admin_teacher_path

app/views/admin/teachers/new.html.haml
%h1 Donar d'alta un professor
= render 'form'

= link_to 'Tornar', admin_teachers_path

app/views/admin/teachers/show.html.haml
%p
  %b Nom i cognom
  = @teacher.name + " " + @teacher.surname
  - unless @teacher.avatar_url.nil?
    %p= image_tag @teacher.avatar_url.to_s

%p
  %b Data neixament
  = @teacher.birthday

%p
  %b Departament
  = @teacher.department.try(:name)

%p
  %b Àrea de recerca
  = @teacher.research_area

%p
  %b Despatx
  = @teacher.office

%p= link_to 'Editar', edit_admin_teacher_path(@teacher)
%p= link_to 'Llistat de professors', admin_teachers_path