config/routes.rb
Web::Application.routes.draw do

  mount Mercury::Engine => '/'

  # Support both GET and POST for callbacks
  %w(get post).each do |method|
    send method, "/auth/:provider/callback" => "teachers#update"
  end

  scope ":locale", locale: /es|ca|en/ do
    Mercury::Engine.routes

    devise_for :users

    root :to => "home#index"

    resources :teachers, :except => [:new,:create] do
      get :my_spaces
      resources :web_spaces do
        resources :pages do
          member { put :mercury_update }
        end
      end
    end

    namespace :admin do
      resources :teachers
      resources :departments
    end
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")
end

app/models/department.rb
class Department < ActiveRecord::Base
  #Associations
  has_many :teachers

  #Validations
  validates :name, :presence => true
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < Admin::AdminController
  inherit_resources
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/admin/departments/_form.html.haml
= form_for([:admin, @department]) do |f|
  .field
    =f.label :nom
    %br
    =f.text_field :name
  .field
    =f.label :descripcio
    %br
    =f.text_field :description
  .actions
    =f.submit 'Crear/Modificar'

app/views/admin/departments/edit.html.haml
%h1 Editar un departament:

=render 'form'

%br
=link_to 'Mostar', admin_department_path(@department)
%br
=link_to 'Tornar', admin_departments_path

app/views/admin/departments/index.html.haml
%h1 Llistat de departaments

#departments_admin
  %table
    %tr
      %th.title Nom
      %th.title Descripció
      %th
      %th
      %th
      - @departments.each do |department|
        %tr
          %td=department.name
          %td=department.description
          %td=link_to 'Mostrar', admin_department_path(department)
          %td=link_to 'Editar', edit_admin_department_path(department)
          %td=link_to 'Eliminar', admin_department_path(department), :confirm => 'Estàs segur?', :method => :delete
  %br
  =link_to 'Crear un nou departament', new_admin_department_path

app/views/admin/departments/new.html.haml
%h1 Crear un nou departament

=render 'form'

=link_to 'Tornar', admin_departments_path

app/views/admin/departments/show.html.haml
%h1 Dades del departament

%p
#notice
  =notice
%p
  %b Nom:
  =@department.name

%p
  %b Descripció:
  = @department.description

%br
=link_to 'Editar', edit_admin_department_path(@department)
%br
=link_to 'Tornar', admin_departments_path