config/routes.rb
Web::Application.routes.draw do

  mount Mercury::Engine => '/'

  # Support both GET and POST for callbacks
  %w(get post).each do |method|
    send method, "/auth/:provider/callback" => "teachers#update"
  end

  scope ":locale", locale: /es|ca|en/ do
    Mercury::Engine.routes

    devise_for :users

    root :to => "home#index"

    resources :teachers, :except => [:new,:create] do
      get :my_spaces
      resources :web_spaces do
        resources :pages do
          member { put :mercury_update }
        end
      end
    end

    namespace :admin do
      resources :teachers
      resources :departments
    end
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")
end

app/models/teacher.rb
class Teacher < User
  # Associations
  belongs_to :department
  has_many :web_spaces

  # Carrierwave avatar uploader
  mount_uploader :avatar, AvatarUploader

  # Attr Accessibles
  attr_accessible :name, :surname, :birthday, :office, :department_id, :research_area, :avatar

  # Virtual Attributes
  validates :name,    :presence => true
  validates :surname, :presence => true
  validates :email,   :presence => true
  validates :department, :presence => true

  # Searchable
  searchable do
    text :name
    text :surname
    text :email
    text :department
    text :research_area
  end
end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < Admin::AdminController
  inherit_resources
  before_filter :load_departments, :only => [:new,:create,:edit,:update]

  def update
    # Don't update password if it is blank
    params[:teacher][:password] = nil if params[:teacher][:password].blank?
    params[:teacher][:password_confirmation] = nil if params[:teacher][:password].blank?
    update!
  end
end

app/controllers/teachers_controller.rb
#encoding: utf-8
class TeachersController < AuthorizedController
  inherit_resources
  before_filter :load_departments, :only => [:index,:edit,:update]
  #load_and_authorize_resource :teacher

  actions :index, :show, :edit, :update

  def index
    @search = Teacher.search(params[:search])
    @teachers = @search.paginate(:page => params[:page], :per_page => 10)
  end

  def update
    if params[:teacher][:password].blank? || params[:teacher][:password_confirmation].blank?
      params[:teacher][:password] = nil
      params[:teacher][:password_confirmation] = nil
    end
    update! do |format|
      format.html do
        # Don't update password if it is blank
        redirect_to edit_teacher_path(current_user), notice: t('alerts.profile_updated')
      end
    end
  end

  def my_spaces
    @teacher = User.find(current_user)
    @my_web_spaces = WebSpace.where(:teacher_id => current_user)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.haml
= form_for @teacher, :html => { :multipart => true} do |f|
  -if @teacher.errors.any?
    %div#error_explanation
      %h2= pluralize(@teacher.errors.count, "error")
      %ul
      =@teacher.errors.full_messages.each do |msg|
        %li= msg
  %div.field
    = f.label :name
    = f.text_field :name

  %div.field
    = f.label :surname
    = f.text_field :surname
    
  %div.field
    = f.label :birthday
    = date_select("teacher", "birthday", :order => [:day, :month, :year], :start_year => 1900, :use_month_numbers => true, :default => { :day => 1, :month => 1 } )

  %div.field
    = f.label :department_id
    = f.select :department_id, @departments.collect{|d| [d.name, d.id]},{:include_blank => true}

  %div.field
    = f.label :research_area
    = f.text_field :research_area

  %div.field
    = f.label :office
    = f.text_field :office

  %div.field
    = f.label :avatar
    = f.file_field :avatar

  %div.ations
    = f.submit

app/views/teachers/edit.html.haml
%h1= t('.title')

#edit_teacher
  = form_for @teacher, :validate => true do |f|
    = f.label t('.name')
    = f.text_field :name

    = f.label t('.surname')
    = f.text_field :surname

    = f.label t('.email')
    = f.text_field :email, autocomplete: "off"

    = f.label t('.password')
    = f.password_field :password, autocomplete: "off"

    = f.label t('.confirmation')
    = f.password_field :password_confirmation

    = f.label t('.birthday')
    = date_select("teacher", "birthday", :order => [:day, :month, :year], :start_year => 1900, :use_month_numbers => true, :default => { :day => 1, :month => 1 } )

    = f.label t('.department')
    = f.select :department_id, @departments.collect{|d| [d.name, d.id]}

    = f.label t('.research')
    = f.text_field :research_area

    = f.label t('.office')
    = f.text_field :office

    = f.label t('.avatar')
    = f.file_field :avatar

    %br
    = f.submit t('.update'), :class => "btn btn-success"
    = link_to t('.twitter'), '/auth/twitter', :class => "btn btn-primary"

app/views/teachers/index.html.haml
%h1= t('.title')

%table{:class => "table table-bordered table-striped"}
  %thead
    %tr
      %td
      %td= sort_link @search, t('.name')
      %td= sort_link @search, t('.surname')
      %td= sort_link @search, t('.email')
      %td= sort_link @search, t('.research')
      %td

    %tbody
    - @teachers.each do |teacher|
      %tr
        %td= image_tag teacher.avatar_url
        %td= teacher.name
        %td= teacher.surname
        %td= teacher.email
        %td= teacher.research_area
        %td
          = link_to t('.see'), teacher, :class => "btn btn-small"

.pagination{:class => "pagination-centered"}
  = will_paginate @teachers

app/views/teachers/my_spaces.html.haml
%h1= t('teachers.my_spaces.title')

%table{:class => "table table-striped"}
  %thead
    %td= t('web_spaces.index.title')
    %td= t('web_spaces.index.description')
    %td= t('web_spaces.index.actions')
  %tbody
    - @my_web_spaces.each do |web_space|
      %tr
        %td= link_to(web_space.name.upcase, teacher_web_space_page_path(web_space.teacher, web_space, web_space.pages.first))
        %td= web_space.content
        %td
          = link_to t('teachers.my_spaces.delete'), teacher_web_space_path(@teacher, web_space), :confirm => t('alerts.sure'), :method => :delete, :class => "btn btn-danger"
          = link_to t('teachers.my_spaces.change'), edit_teacher_web_space_path(@teacher, web_space), :class => "btn btn-info"

= link_to t('teachers.my_spaces.create'), new_teacher_web_space_path(@teacher), :class => "btn btn-primary"

app/views/teachers/new.html.haml
%h1 New teacher
= render 'form'

= link_to 'Back', teachers_path

app/views/teachers/show.html.haml
%h1=@teacher.name + " " + @teacher.surname
%p
  %p= image_tag @teacher.avatar_url.to_s

%p
  %b= t('.birthday')
  = @teacher.birthday.strftime('%d/%m/%Y')

%p
  %b= t('.department')
  = @teacher.department.try(:name)

%p
  %b= t('.research')
  = @teacher.research_area

%p
  %b= t('.office')
  = @teacher.office

%p= mail_to @teacher.email, t('.contact'), :subject => t('.subject'),:target => "_blank", :class => "btn btn-primary"

- unless @teacher.web_spaces.empty?
  %h2= t('.webspaces')
  %table{:class => "table table-striped"}
    %tdbody
      - @teacher.web_spaces.each do |web_space|
        %tr
          %td= link_to web_space.name, teacher_web_space_page_path(@teacher, web_space, web_space.pages.first)
          %td= web_space.content