config/routes.rb
Web::Application.routes.draw do

  mount Mercury::Engine => '/'

  # Support both GET and POST for callbacks
  %w(get post).each do |method|
    send method, "/auth/:provider/callback" => "teachers#update"
  end

  scope ":locale", locale: /es|ca|en/ do
    Mercury::Engine.routes

    devise_for :users

    root :to => "home#index"

    resources :teachers, :except => [:new,:create] do
      get :my_spaces
      resources :web_spaces do
        resources :pages do
          member { put :mercury_update }
        end
      end
    end

    namespace :admin do
      resources :teachers
      resources :departments
    end
  end

  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")
end

app/views/layouts/application.haml
!!! html
%html
  %head
    %title PFC - CMS
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = csrf_meta_tag
    = javascript_include_tag 'application'
    = stylesheet_link_tag 'application'
  %body
    #wrapper
      - unless current_user.nil?
        #header{:class => "navbar navbar-inner"}
          .container
            = link_to "CMS - Web", "#", :class => "brand"
            .nav-collapse_in_collapse
              %ul.nav
                %li.divider-vertical
                %li= link_to t('menu.news'), root_path
                %li.divider-vertical
                %li= link_to t('menu.spaces'), teacher_web_spaces_path(current_user)
                %li.divider-vertical
                %li= link_to t('menu.personal'), teachers_path
                %li.divider-vertical
                %li{:class => "dropdown", :id =>"menu1"}
                  %a{:class => 'btn-mini dropdown-toggle', "data-toggle" => 'dropdown', :href => '#'}
                    - unless current_user.admin?
                      = "#{current_user.name} #{current_user.surname}"
                      %i{:class => 'icon-chevron-down'}
                    - else
                      = "Admin"
                      %i{:class => 'icon-chevron-down'}
                    %ul{:class => "dropdown-menu"}
                      - unless current_user.admin?
                        %li{:class => "nav-header"}= t('menu.actions')
                        %li= link_to t('menu.edit'), edit_teacher_path(current_user)
                        %li= link_to t('menu.my_spaces'), teacher_my_spaces_path(current_user)
                      %li= link_to t('menu.exit'), destroy_user_session_path
                      %li.divider
                      %li{:class => "nav-header"}= t('menu.language')
                      %li= link_to "Català", locale: "ca"
                      %li= link_to "English", locale: "en"
                      %li= link_to "Español", locale: "es"
                %li.divider-vertical
            - unless current_user.nil? && current_user.admin?
              = form_tag root_path, :method => :get, :class => "form-search pull-right" do
                = text_field_tag :search, params[:search], :placeholder => t('menu.find'), value: "", :class => "search-query span3"
                %i{:class => "icon-search"}
            - else
              #nil_title
                %h1= t('menu.nil_title')
      #content.container
        - unless flash[:notice].nil?
          #success{:class => "alert alert-success"}
            %button{:class => "close", "data-dismiss" => "alert"} x
            = flash[:notice]
        - unless flash[:error].nil?
          #error{:class => "alert alert-error"}
            %button{:class => "close", "data-dismiss" => "alert"} x
            = flash[:error]
        - unless flash[:alert].nil?
          #alert{:class => "alert alert-info"}
            %button{:class => "close", "data-dismiss" => "alert"} x
            = flash[:alert]
        = yield
      #footer
        %ul.footer_nav
          - if user_signed_in? && current_user.admin?
            %li= link_to(t('menu.teachers'), admin_teachers_path)
            %li= link_to(t('menu.departments'), admin_departments_path)

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title PFC - Gestor de contingut
    %meta{:charset => "utf-8"}
    = csrf_meta_tag
    = javascript_include_tag "application"
    = stylesheet_link_tag "application"
    = javascript_include_tag 'ckeditor/ckeditor' 	
  %body
    #wrapper
      #header
        %ul#user_nav
          - if user_signed_in?
            %li= link_to "Sortir", destroy_user_session_path
          - else
            %li= link_to "Registrar-se", new_user_registration_path 
            %li= link_to "Entrar", new_user_session_path
        %ul#menu
          - if user_signed_in?
            %li= link_to "Notícies", root_path
            %li= link_to "Gestionar els meus espai webs", teacher_web_spaces_path(current_user)
            %li= link_to "Espais webs", teacher_web_spaces_path(current_user)
            %li= link_to "Professors i investigadors", teachers_path
      #content
        - unless flash[:notice].nil?
          %p.flash= flash[:notice]
        = yield
      #footer
        - if user_signed_in? && current_user.admin?
          %li= link_to "Professors", admin_teachers_path
          %li= link_to "Departaments", admin_departments_path

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  null, // 'form', or 'json' (default json)
        saveMethod: null, // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>